(deftheme shomasd
  "Created 2014-08-16.")

(custom-theme-set-faces
 'shomasd
 '(cursor ((t (:foreground "#DCDCCC" :background "#FFFFEF"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#FDECBC"))))
 '(minibuffer-prompt ((t (:foreground "#FDECBC"))))
 '(highlight ((t (:background "#2D2D2D"))))
 '(region ((t (:background "midnight blue"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#4E4E4E"))))
 '(trailing-whitespace ((t (:background "#D9A0A0"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#DCDCCC"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6C8C6C"))))
 '(font-lock-comment-face ((t (:foreground "#8CAC8C"))))
 '(font-lock-constant-face ((t (:foreground "DodgerBlue1"))))
 '(font-lock-doc-face ((t (:foreground "#ACD2AC"))))
 '(font-lock-function-name-face ((t (:foreground "#A0EDF0"))))
 '(font-lock-keyword-face ((t (:weight thin :foreground "green1"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#FDECBC"))))
 '(font-lock-preprocessor-face ((t (:foreground "#9CC7FB"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#8CAC8C"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#FDECBC"))))
 '(font-lock-string-face ((t (:foreground "#D9A0A0"))))
 '(font-lock-type-face ((t (:foreground "Lightpink1"))))
 '(font-lock-variable-name-face ((t (:foreground "orange2"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#DDCC9C"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#FDECBC"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#DDCC9C"))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#3E3E3E"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#FDECBC" :background "#202020"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:background "#202020" :foreground "#9CBF9C" :box (:line-width -1 :style released-button)))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#FDECBC"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :style released-button) :foreground "#6C8C6C" :background "#2D2D2D"))))
 '(isearch ((t (:weight bold :foreground "#DDCC9C" :background "#4E4E4E"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#996060"))))
 '(lazy-highlight ((t (:weight bold :foreground "#DDCC9C" :background "#2D2D2D"))))
 '(match ((t (:weight bold :foreground "#ECBC9C" :background "#202020"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:family "Menlo" :foundry "nil" :width normal :height 100 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#DCDCCC" :background "#313131" :stipple nil :inherit nil)))))

(provide-theme 'shomasd)
